POST http://localhost:3001/api/items
Content-Type: application/json

{
  "author": {
    "name": "Juan Camilo",
    "lastname": "Zapata"
  },
  "item": {
    "title": "itemasdsadssss",
    "price": {
      "currency": "Pesos",
      "amount": 1,
      "decimals": 2
    },
    "picture": "/asd/asdasd/",
    "condition": "Nuevo",
    "free_shipping": false,
    "sold_quantity": 2,
    "description": "Ipad adsad"
  }
}